/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donation {
    id: bigint;
    status: DonationStatus;
    spoilageSafe: boolean;
    city: string;
    submittedAt: Time;
    pickupDeadline: Time;
    pickupAddress: string;
    storageCondition: StorageCondition;
    hotelPrincipal: Principal;
    timeSinceCooked: number;
    matchedNGOPrincipal?: Principal;
    quantityKg: number;
    foodType: FoodType;
}
export type Time = bigint;
export interface SystemAnalytics {
    totalVolunteers: bigint;
    wasteReducedKg: number;
    co2SavedKg: number;
    totalUsers: bigint;
    totalDonations: bigint;
    citywiseStats: Array<CitywiseStats>;
    totalKgRedistributed: number;
}
export interface NGOProfile {
    principal: Principal;
    active: boolean;
    orgName: string;
    foodTypePreferences: Array<FoodType>;
    dailyCapacityKg: number;
    currentDailyReceivedKg: number;
    locationAddress: string;
}
export interface HotelProfile {
    principal: Principal;
    active: boolean;
    name: string;
}
export interface VolunteerProfile {
    principal: Principal;
    active: boolean;
    city: string;
    name: string;
    availabilityStatus: string;
}
export interface UserProfile {
    displayName: string;
    appRole: AppUserRole;
}
export interface CitywiseStats {
    city: string;
    totalKg: number;
    donationCount: bigint;
}
export enum AppUserRole {
    ngo = "ngo",
    admin = "admin",
    hotel = "hotel",
    volunteer = "volunteer"
}
export enum DonationStatus {
    pending = "pending",
    completed = "completed",
    inTransit = "inTransit",
    unmatched = "unmatched",
    matched = "matched",
    rejected = "rejected",
    accepted = "accepted"
}
export enum FoodType {
    desserts = "desserts",
    other = "other",
    fish = "fish",
    rice = "rice",
    curry = "curry",
    bread = "bread",
    vegetables = "vegetables",
    dairy = "dairy"
}
export enum StorageCondition {
    hot = "hot",
    roomTemperature = "roomTemperature",
    refrigerated = "refrigerated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDonation(donationId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateUser(principal: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentRole(): Promise<AppUserRole | null>;
    getDonation(donationId: bigint): Promise<Donation | null>;
    getHotelAverageRating(hotelPrincipal: Principal): Promise<number>;
    getHotelProfile(hotelId: Principal): Promise<HotelProfile | null>;
    getMyHotelDonations(): Promise<Array<Donation>>;
    getMyHotelProfile(): Promise<HotelProfile | null>;
    getMyNGODonations(): Promise<Array<Donation>>;
    getMyNGOProfile(): Promise<NGOProfile | null>;
    getMyVolunteerAssignments(): Promise<Array<Donation>>;
    getMyVolunteerProfile(): Promise<VolunteerProfile | null>;
    getNGOProfile(ngoId: Principal): Promise<NGOProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVolunteerProfile(volunteerId: Principal): Promise<VolunteerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllDonations(): Promise<Array<Donation>>;
    listAllUsers(): Promise<[Array<HotelProfile>, Array<NGOProfile>, Array<VolunteerProfile>]>;
    listVolunteerAssignments(): Promise<Array<Donation>>;
    registerHotel(name: string): Promise<void>;
    registerNGO(orgName: string, locationAddress: string, foodTypePreferences: Array<FoodType>, dailyCapacityKg: number): Promise<void>;
    /**
     * / Register the caller as a Volunteer. Requires authenticated user.
     */
    registerVolunteer(name: string, city: string, availabilityStatus: string): Promise<void>;
    rejectDonation(donationId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDonation(foodType: FoodType, quantityKg: number, timeSinceCooked: number, storageCondition: StorageCondition, pickupAddress: string, pickupDeadline: Time, city: string): Promise<[boolean, Principal | null]>;
    submitFeedback(donationId: bigint, rating: bigint, comment: string): Promise<void>;
    systemAnalytics(): Promise<SystemAnalytics>;
    updateDonationStatus(donationId: bigint, newStatus: DonationStatus): Promise<void>;
    updateVolunteerStatus(active: boolean, availabilityStatus: string): Promise<void>;
}
import type { AppUserRole as _AppUserRole, Donation as _Donation, DonationStatus as _DonationStatus, FoodType as _FoodType, HotelProfile as _HotelProfile, NGOProfile as _NGOProfile, StorageCondition as _StorageCondition, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VolunteerProfile as _VolunteerProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDonation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDonation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentRole(): Promise<AppUserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRole();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRole();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonation(arg0: bigint): Promise<Donation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonation(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonation(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelAverageRating(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelAverageRating(arg0);
            return result;
        }
    }
    async getHotelProfile(arg0: Principal): Promise<HotelProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHotelDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHotelDonations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHotelDonations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHotelProfile(): Promise<HotelProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHotelProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHotelProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNGODonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNGODonations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNGODonations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNGOProfile(): Promise<NGOProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNGOProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNGOProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVolunteerAssignments(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVolunteerAssignments();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVolunteerAssignments();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVolunteerProfile(): Promise<VolunteerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVolunteerProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVolunteerProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNGOProfile(arg0: Principal): Promise<NGOProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNGOProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNGOProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteerProfile(arg0: Principal): Promise<VolunteerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteerProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteerProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllDonations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllDonations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<[Array<HotelProfile>, Array<NGOProfile>, Array<VolunteerProfile>]> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return [
                    result[0],
                    from_candid_vec_n28(this._uploadFile, this._downloadFile, result[1]),
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return [
                result[0],
                from_candid_vec_n28(this._uploadFile, this._downloadFile, result[1]),
                result[2]
            ];
        }
    }
    async listVolunteerAssignments(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVolunteerAssignments();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVolunteerAssignments();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerHotel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerHotel(arg0);
            return result;
        }
    }
    async registerNGO(arg0: string, arg1: string, arg2: Array<FoodType>, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNGO(arg0, arg1, to_candid_vec_n29(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNGO(arg0, arg1, to_candid_vec_n29(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async registerVolunteer(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectDonation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDonation(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDonation(arg0: FoodType, arg1: number, arg2: number, arg3: StorageCondition, arg4: string, arg5: Time, arg6: string): Promise<[boolean, Principal | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDonation(to_candid_FoodType_n30(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_StorageCondition_n36(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return [
                    result[0],
                    from_candid_opt_n18(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDonation(to_candid_FoodType_n30(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_StorageCondition_n36(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return [
                result[0],
                from_candid_opt_n18(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async submitFeedback(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async systemAnalytics(): Promise<SystemAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.systemAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.systemAnalytics();
            return result;
        }
    }
    async updateDonationStatus(arg0: bigint, arg1: DonationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationStatus(arg0, to_candid_DonationStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationStatus(arg0, to_candid_DonationStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVolunteerStatus(arg0: boolean, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVolunteerStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVolunteerStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppUserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DonationStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationStatus): DonationStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FoodType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodType): FoodType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_NGOProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NGOProfile): NGOProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StorageCondition_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StorageCondition): StorageCondition {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUserRole]): AppUserRole | null {
    return value.length === 0 ? null : from_candid_AppUserRole_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donation]): Donation | null {
    return value.length === 0 ? null : from_candid_Donation_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HotelProfile]): HotelProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NGOProfile]): NGOProfile | null {
    return value.length === 0 ? null : from_candid_NGOProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VolunteerProfile]): VolunteerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DonationStatus;
    spoilageSafe: boolean;
    city: string;
    submittedAt: _Time;
    pickupDeadline: _Time;
    pickupAddress: string;
    storageCondition: _StorageCondition;
    hotelPrincipal: Principal;
    timeSinceCooked: number;
    matchedNGOPrincipal: [] | [Principal];
    quantityKg: number;
    foodType: _FoodType;
}): {
    id: bigint;
    status: DonationStatus;
    spoilageSafe: boolean;
    city: string;
    submittedAt: Time;
    pickupDeadline: Time;
    pickupAddress: string;
    storageCondition: StorageCondition;
    hotelPrincipal: Principal;
    timeSinceCooked: number;
    matchedNGOPrincipal?: Principal;
    quantityKg: number;
    foodType: FoodType;
} {
    return {
        id: value.id,
        status: from_candid_DonationStatus_n14(_uploadFile, _downloadFile, value.status),
        spoilageSafe: value.spoilageSafe,
        city: value.city,
        submittedAt: value.submittedAt,
        pickupDeadline: value.pickupDeadline,
        pickupAddress: value.pickupAddress,
        storageCondition: from_candid_StorageCondition_n16(_uploadFile, _downloadFile, value.storageCondition),
        hotelPrincipal: value.hotelPrincipal,
        timeSinceCooked: value.timeSinceCooked,
        matchedNGOPrincipal: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.matchedNGOPrincipal)),
        quantityKg: value.quantityKg,
        foodType: from_candid_FoodType_n19(_uploadFile, _downloadFile, value.foodType)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    active: boolean;
    orgName: string;
    foodTypePreferences: Array<_FoodType>;
    dailyCapacityKg: number;
    currentDailyReceivedKg: number;
    locationAddress: string;
}): {
    principal: Principal;
    active: boolean;
    orgName: string;
    foodTypePreferences: Array<FoodType>;
    dailyCapacityKg: number;
    currentDailyReceivedKg: number;
    locationAddress: string;
} {
    return {
        principal: value.principal,
        active: value.active,
        orgName: value.orgName,
        foodTypePreferences: from_candid_vec_n26(_uploadFile, _downloadFile, value.foodTypePreferences),
        dailyCapacityKg: value.dailyCapacityKg,
        currentDailyReceivedKg: value.currentDailyReceivedKg,
        locationAddress: value.locationAddress
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    appRole: _AppUserRole;
}): {
    displayName: string;
    appRole: AppUserRole;
} {
    return {
        displayName: value.displayName,
        appRole: from_candid_AppUserRole_n6(_uploadFile, _downloadFile, value.appRole)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inTransit: null;
} | {
    unmatched: null;
} | {
    matched: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): DonationStatus {
    return "pending" in value ? DonationStatus.pending : "completed" in value ? DonationStatus.completed : "inTransit" in value ? DonationStatus.inTransit : "unmatched" in value ? DonationStatus.unmatched : "matched" in value ? DonationStatus.matched : "rejected" in value ? DonationStatus.rejected : "accepted" in value ? DonationStatus.accepted : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hot: null;
} | {
    roomTemperature: null;
} | {
    refrigerated: null;
}): StorageCondition {
    return "hot" in value ? StorageCondition.hot : "roomTemperature" in value ? StorageCondition.roomTemperature : "refrigerated" in value ? StorageCondition.refrigerated : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desserts: null;
} | {
    other: null;
} | {
    fish: null;
} | {
    rice: null;
} | {
    curry: null;
} | {
    bread: null;
} | {
    vegetables: null;
} | {
    dairy: null;
}): FoodType {
    return "desserts" in value ? FoodType.desserts : "other" in value ? FoodType.other : "fish" in value ? FoodType.fish : "rice" in value ? FoodType.rice : "curry" in value ? FoodType.curry : "bread" in value ? FoodType.bread : "vegetables" in value ? FoodType.vegetables : "dairy" in value ? FoodType.dairy : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    admin: null;
} | {
    hotel: null;
} | {
    volunteer: null;
}): AppUserRole {
    return "ngo" in value ? AppUserRole.ngo : "admin" in value ? AppUserRole.admin : "hotel" in value ? AppUserRole.hotel : "volunteer" in value ? AppUserRole.volunteer : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodType>): Array<FoodType> {
    return value.map((x)=>from_candid_FoodType_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NGOProfile>): Array<NGOProfile> {
    return value.map((x)=>from_candid_NGOProfile_n24(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_DonationStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): _DonationStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_FoodType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): _FoodType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_StorageCondition_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StorageCondition): _StorageCondition {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    appRole: AppUserRole;
}): {
    displayName: string;
    appRole: _AppUserRole;
} {
    return {
        displayName: value.displayName,
        appRole: to_candid_AppUserRole_n34(_uploadFile, _downloadFile, value.appRole)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): {
    desserts: null;
} | {
    other: null;
} | {
    fish: null;
} | {
    rice: null;
} | {
    curry: null;
} | {
    bread: null;
} | {
    vegetables: null;
} | {
    dairy: null;
} {
    return value == FoodType.desserts ? {
        desserts: null
    } : value == FoodType.other ? {
        other: null
    } : value == FoodType.fish ? {
        fish: null
    } : value == FoodType.rice ? {
        rice: null
    } : value == FoodType.curry ? {
        curry: null
    } : value == FoodType.bread ? {
        bread: null
    } : value == FoodType.vegetables ? {
        vegetables: null
    } : value == FoodType.dairy ? {
        dairy: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    ngo: null;
} | {
    admin: null;
} | {
    hotel: null;
} | {
    volunteer: null;
} {
    return value == AppUserRole.ngo ? {
        ngo: null
    } : value == AppUserRole.admin ? {
        admin: null
    } : value == AppUserRole.hotel ? {
        hotel: null
    } : value == AppUserRole.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StorageCondition): {
    hot: null;
} | {
    roomTemperature: null;
} | {
    refrigerated: null;
} {
    return value == StorageCondition.hot ? {
        hot: null
    } : value == StorageCondition.roomTemperature ? {
        roomTemperature: null
    } : value == StorageCondition.refrigerated ? {
        refrigerated: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inTransit: null;
} | {
    unmatched: null;
} | {
    matched: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == DonationStatus.pending ? {
        pending: null
    } : value == DonationStatus.completed ? {
        completed: null
    } : value == DonationStatus.inTransit ? {
        inTransit: null
    } : value == DonationStatus.unmatched ? {
        unmatched: null
    } : value == DonationStatus.matched ? {
        matched: null
    } : value == DonationStatus.rejected ? {
        rejected: null
    } : value == DonationStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FoodType>): Array<_FoodType> {
    return value.map((x)=>to_candid_FoodType_n30(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
