/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'ngo' : null } |
  { 'admin' : null } |
  { 'hotel' : null } |
  { 'volunteer' : null };
export interface CitywiseStats {
  'city' : string,
  'totalKg' : number,
  'donationCount' : bigint,
}
export interface Donation {
  'id' : bigint,
  'status' : DonationStatus,
  'spoilageSafe' : boolean,
  'city' : string,
  'submittedAt' : Time,
  'pickupDeadline' : Time,
  'pickupAddress' : string,
  'storageCondition' : StorageCondition,
  'hotelPrincipal' : Principal,
  'timeSinceCooked' : number,
  'matchedNGOPrincipal' : [] | [Principal],
  'quantityKg' : number,
  'foodType' : FoodType,
}
export type DonationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inTransit' : null } |
  { 'unmatched' : null } |
  { 'matched' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type FoodType = { 'desserts' : null } |
  { 'other' : null } |
  { 'fish' : null } |
  { 'rice' : null } |
  { 'curry' : null } |
  { 'bread' : null } |
  { 'vegetables' : null } |
  { 'dairy' : null };
export interface HotelProfile {
  'principal' : Principal,
  'active' : boolean,
  'name' : string,
}
export interface NGOProfile {
  'principal' : Principal,
  'active' : boolean,
  'orgName' : string,
  'foodTypePreferences' : Array<FoodType>,
  'dailyCapacityKg' : number,
  'currentDailyReceivedKg' : number,
  'locationAddress' : string,
}
export type StorageCondition = { 'hot' : null } |
  { 'roomTemperature' : null } |
  { 'refrigerated' : null };
export interface SystemAnalytics {
  'totalVolunteers' : bigint,
  'wasteReducedKg' : number,
  'co2SavedKg' : number,
  'totalUsers' : bigint,
  'totalDonations' : bigint,
  'citywiseStats' : Array<CitywiseStats>,
  'totalKgRedistributed' : number,
}
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'appRole' : AppUserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VolunteerProfile {
  'principal' : Principal,
  'active' : boolean,
  'city' : string,
  'name' : string,
  'availabilityStatus' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDonation' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRole' : ActorMethod<[], [] | [AppUserRole]>,
  'getDonation' : ActorMethod<[bigint], [] | [Donation]>,
  'getHotelAverageRating' : ActorMethod<[Principal], number>,
  'getHotelProfile' : ActorMethod<[Principal], [] | [HotelProfile]>,
  'getMyHotelDonations' : ActorMethod<[], Array<Donation>>,
  'getMyHotelProfile' : ActorMethod<[], [] | [HotelProfile]>,
  'getMyNGODonations' : ActorMethod<[], Array<Donation>>,
  'getMyNGOProfile' : ActorMethod<[], [] | [NGOProfile]>,
  'getMyVolunteerAssignments' : ActorMethod<[], Array<Donation>>,
  'getMyVolunteerProfile' : ActorMethod<[], [] | [VolunteerProfile]>,
  'getNGOProfile' : ActorMethod<[Principal], [] | [NGOProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteerProfile' : ActorMethod<[Principal], [] | [VolunteerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllDonations' : ActorMethod<[], Array<Donation>>,
  'listAllUsers' : ActorMethod<
    [],
    [Array<HotelProfile>, Array<NGOProfile>, Array<VolunteerProfile>]
  >,
  'listVolunteerAssignments' : ActorMethod<[], Array<Donation>>,
  'registerHotel' : ActorMethod<[string], undefined>,
  'registerNGO' : ActorMethod<
    [string, string, Array<FoodType>, number],
    undefined
  >,
  /**
   * / Register the caller as a Volunteer. Requires authenticated user.
   */
  'registerVolunteer' : ActorMethod<[string, string, string], undefined>,
  'rejectDonation' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDonation' : ActorMethod<
    [FoodType, number, number, StorageCondition, string, Time, string],
    [boolean, [] | [Principal]]
  >,
  'submitFeedback' : ActorMethod<[bigint, bigint, string], undefined>,
  'systemAnalytics' : ActorMethod<[], SystemAnalytics>,
  'updateDonationStatus' : ActorMethod<[bigint, DonationStatus], undefined>,
  'updateVolunteerStatus' : ActorMethod<[boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];