/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'ngo' : null } |
  { 'admin' : null } |
  { 'hotel' : null };
export interface Donation {
  'id' : bigint,
  'status' : DonationStatus,
  'spoilageSafe' : boolean,
  'submittedAt' : Time,
  'pickupDeadline' : Time,
  'pickupAddress' : string,
  'storageCondition' : StorageCondition,
  'hotelPrincipal' : Principal,
  'timeSinceCooked' : number,
  'matchedNGOPrincipal' : [] | [Principal],
  'quantityKg' : number,
  'foodType' : FoodType,
}
export type DonationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inTransit' : null } |
  { 'unmatched' : null } |
  { 'matched' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type FoodType = { 'desserts' : null } |
  { 'other' : null } |
  { 'fish' : null } |
  { 'rice' : null } |
  { 'curry' : null } |
  { 'bread' : null } |
  { 'vegetables' : null } |
  { 'dairy' : null };
export interface HotelProfile {
  'principal' : Principal,
  'active' : boolean,
  'name' : string,
}
export interface NGOProfile {
  'principal' : Principal,
  'active' : boolean,
  'orgName' : string,
  'foodTypePreferences' : Array<FoodType>,
  'dailyCapacityKg' : number,
  'currentDailyReceivedKg' : number,
  'locationAddress' : string,
}
export type StorageCondition = { 'hot' : null } |
  { 'roomTemperature' : null } |
  { 'refrigerated' : null };
export interface SystemAnalytics {
  'wasteReducedKg' : number,
  'totalUsers' : bigint,
  'totalDonations' : bigint,
  'totalKgRedistributed' : number,
}
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'appRole' : AppUserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Accept a donation. Only the matched NGO principal can call this.
   */
  'acceptDonation' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Deactivate a user (hotel or NGO). Admin only.
   */
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Get the caller's own UserProfile. Requires authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRole' : ActorMethod<[], [] | [AppUserRole]>,
  /**
   * / Get a donation record. Any authenticated user can view.
   */
  'getDonation' : ActorMethod<[bigint], [] | [Donation]>,
  /**
   * / Get average rating for a hotel based on feedback on its completed donations.
   */
  'getHotelAverageRating' : ActorMethod<[Principal], number>,
  /**
   * / Get a hotel profile. Any authenticated user can view.
   */
  'getHotelProfile' : ActorMethod<[Principal], [] | [HotelProfile]>,
  /**
   * / Get all donations for the calling hotel. Hotel role only.
   */
  'getMyHotelDonations' : ActorMethod<[], Array<Donation>>,
  /**
   * / Get the calling hotel's own profile. Hotel role only.
   */
  'getMyHotelProfile' : ActorMethod<[], [] | [HotelProfile]>,
  /**
   * / Get all donations matched to the calling NGO. NGO role only.
   */
  'getMyNGODonations' : ActorMethod<[], Array<Donation>>,
  /**
   * / Get the calling NGO's own profile. NGO role only.
   */
  'getMyNGOProfile' : ActorMethod<[], [] | [NGOProfile]>,
  /**
   * / Get an NGO profile. Any authenticated user can view.
   */
  'getNGOProfile' : ActorMethod<[Principal], [] | [NGOProfile]>,
  /**
   * / Get another user's profile. Caller can view own profile; admins can view any.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all donations with enriched info. Admin only.
   */
  'listAllDonations' : ActorMethod<[], Array<Donation>>,
  /**
   * / List all hotel and NGO profiles. Admin only.
   */
  'listAllUsers' : ActorMethod<[], [Array<HotelProfile>, Array<NGOProfile>]>,
  /**
   * / Register the caller as a Hotel. Requires authenticated user.
   */
  'registerHotel' : ActorMethod<[string], undefined>,
  /**
   * / Register the caller as an NGO. Requires authenticated user.
   */
  'registerNGO' : ActorMethod<
    [string, string, Array<FoodType>, number],
    undefined
  >,
  /**
   * / Reject a donation and attempt re-matching. Only the matched NGO principal can call this.
   */
  'rejectDonation' : ActorMethod<[bigint], undefined>,
  /**
   * / Save the caller's own UserProfile. Requires authenticated user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a food donation. Only Hotel role users can call this.
   */
  'submitDonation' : ActorMethod<
    [FoodType, number, number, StorageCondition, string, Time],
    [boolean, [] | [Principal]]
  >,
  /**
   * / Submit feedback for a completed donation. Only NGO role users can call this.
   */
  'submitFeedback' : ActorMethod<[bigint, bigint, string], undefined>,
  /**
   * / System analytics. Admin only.
   */
  'systemAnalytics' : ActorMethod<[], SystemAnalytics>,
  /**
   * / Update any donation's status. Admin only.
   */
  'updateDonationStatus' : ActorMethod<[bigint, DonationStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];