/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppUserRole = IDL.Variant({
  'ngo' : IDL.Null,
  'admin' : IDL.Null,
  'hotel' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'appRole' : AppUserRole,
});
export const DonationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inTransit' : IDL.Null,
  'unmatched' : IDL.Null,
  'matched' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const StorageCondition = IDL.Variant({
  'hot' : IDL.Null,
  'roomTemperature' : IDL.Null,
  'refrigerated' : IDL.Null,
});
export const FoodType = IDL.Variant({
  'desserts' : IDL.Null,
  'other' : IDL.Null,
  'fish' : IDL.Null,
  'rice' : IDL.Null,
  'curry' : IDL.Null,
  'bread' : IDL.Null,
  'vegetables' : IDL.Null,
  'dairy' : IDL.Null,
});
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'status' : DonationStatus,
  'spoilageSafe' : IDL.Bool,
  'city' : IDL.Text,
  'submittedAt' : Time,
  'pickupDeadline' : Time,
  'pickupAddress' : IDL.Text,
  'storageCondition' : StorageCondition,
  'hotelPrincipal' : IDL.Principal,
  'timeSinceCooked' : IDL.Float64,
  'matchedNGOPrincipal' : IDL.Opt(IDL.Principal),
  'quantityKg' : IDL.Float64,
  'foodType' : FoodType,
});
export const HotelProfile = IDL.Record({
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'name' : IDL.Text,
});
export const NGOProfile = IDL.Record({
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'orgName' : IDL.Text,
  'foodTypePreferences' : IDL.Vec(FoodType),
  'dailyCapacityKg' : IDL.Float64,
  'currentDailyReceivedKg' : IDL.Float64,
  'locationAddress' : IDL.Text,
});
export const VolunteerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'availabilityStatus' : IDL.Text,
});
export const CitywiseStats = IDL.Record({
  'city' : IDL.Text,
  'totalKg' : IDL.Float64,
  'donationCount' : IDL.Nat,
});
export const SystemAnalytics = IDL.Record({
  'totalVolunteers' : IDL.Nat,
  'wasteReducedKg' : IDL.Float64,
  'co2SavedKg' : IDL.Float64,
  'totalUsers' : IDL.Nat,
  'totalDonations' : IDL.Nat,
  'citywiseStats' : IDL.Vec(CitywiseStats),
  'totalKgRedistributed' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDonation' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRole' : IDL.Func([], [IDL.Opt(AppUserRole)], ['query']),
  'getDonation' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
  'getHotelAverageRating' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getHotelProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(HotelProfile)],
      ['query'],
    ),
  'getMyHotelDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getMyHotelProfile' : IDL.Func([], [IDL.Opt(HotelProfile)], ['query']),
  'getMyNGODonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfile)], ['query']),
  'getMyVolunteerAssignments' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getMyVolunteerProfile' : IDL.Func(
      [],
      [IDL.Opt(VolunteerProfile)],
      ['query'],
    ),
  'getNGOProfile' : IDL.Func([IDL.Principal], [IDL.Opt(NGOProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VolunteerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(HotelProfile), IDL.Vec(NGOProfile), IDL.Vec(VolunteerProfile)],
      ['query'],
    ),
  'listVolunteerAssignments' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'registerHotel' : IDL.Func([IDL.Text], [], []),
  'registerNGO' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(FoodType), IDL.Float64],
      [],
      [],
    ),
  'registerVolunteer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectDonation' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDonation' : IDL.Func(
      [
        FoodType,
        IDL.Float64,
        IDL.Float64,
        StorageCondition,
        IDL.Text,
        Time,
        IDL.Text,
      ],
      [IDL.Bool, IDL.Opt(IDL.Principal)],
      [],
    ),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'systemAnalytics' : IDL.Func([], [SystemAnalytics], ['query']),
  'updateDonationStatus' : IDL.Func([IDL.Nat, DonationStatus], [], []),
  'updateVolunteerStatus' : IDL.Func([IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppUserRole = IDL.Variant({
    'ngo' : IDL.Null,
    'admin' : IDL.Null,
    'hotel' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'appRole' : AppUserRole,
  });
  const DonationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inTransit' : IDL.Null,
    'unmatched' : IDL.Null,
    'matched' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const StorageCondition = IDL.Variant({
    'hot' : IDL.Null,
    'roomTemperature' : IDL.Null,
    'refrigerated' : IDL.Null,
  });
  const FoodType = IDL.Variant({
    'desserts' : IDL.Null,
    'other' : IDL.Null,
    'fish' : IDL.Null,
    'rice' : IDL.Null,
    'curry' : IDL.Null,
    'bread' : IDL.Null,
    'vegetables' : IDL.Null,
    'dairy' : IDL.Null,
  });
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'status' : DonationStatus,
    'spoilageSafe' : IDL.Bool,
    'city' : IDL.Text,
    'submittedAt' : Time,
    'pickupDeadline' : Time,
    'pickupAddress' : IDL.Text,
    'storageCondition' : StorageCondition,
    'hotelPrincipal' : IDL.Principal,
    'timeSinceCooked' : IDL.Float64,
    'matchedNGOPrincipal' : IDL.Opt(IDL.Principal),
    'quantityKg' : IDL.Float64,
    'foodType' : FoodType,
  });
  const HotelProfile = IDL.Record({
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  const NGOProfile = IDL.Record({
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'orgName' : IDL.Text,
    'foodTypePreferences' : IDL.Vec(FoodType),
    'dailyCapacityKg' : IDL.Float64,
    'currentDailyReceivedKg' : IDL.Float64,
    'locationAddress' : IDL.Text,
  });
  const VolunteerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'availabilityStatus' : IDL.Text,
  });
  const CitywiseStats = IDL.Record({
    'city' : IDL.Text,
    'totalKg' : IDL.Float64,
    'donationCount' : IDL.Nat,
  });
  const SystemAnalytics = IDL.Record({
    'totalVolunteers' : IDL.Nat,
    'wasteReducedKg' : IDL.Float64,
    'co2SavedKg' : IDL.Float64,
    'totalUsers' : IDL.Nat,
    'totalDonations' : IDL.Nat,
    'citywiseStats' : IDL.Vec(CitywiseStats),
    'totalKgRedistributed' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDonation' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRole' : IDL.Func([], [IDL.Opt(AppUserRole)], ['query']),
    'getDonation' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
    'getHotelAverageRating' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'getHotelProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(HotelProfile)],
        ['query'],
      ),
    'getMyHotelDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getMyHotelProfile' : IDL.Func([], [IDL.Opt(HotelProfile)], ['query']),
    'getMyNGODonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfile)], ['query']),
    'getMyVolunteerAssignments' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getMyVolunteerProfile' : IDL.Func(
        [],
        [IDL.Opt(VolunteerProfile)],
        ['query'],
      ),
    'getNGOProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NGOProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VolunteerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(HotelProfile), IDL.Vec(NGOProfile), IDL.Vec(VolunteerProfile)],
        ['query'],
      ),
    'listVolunteerAssignments' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'registerHotel' : IDL.Func([IDL.Text], [], []),
    'registerNGO' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(FoodType), IDL.Float64],
        [],
        [],
      ),
    'registerVolunteer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectDonation' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDonation' : IDL.Func(
        [
          FoodType,
          IDL.Float64,
          IDL.Float64,
          StorageCondition,
          IDL.Text,
          Time,
          IDL.Text,
        ],
        [IDL.Bool, IDL.Opt(IDL.Principal)],
        [],
      ),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'systemAnalytics' : IDL.Func([], [SystemAnalytics], ['query']),
    'updateDonationStatus' : IDL.Func([IDL.Nat, DonationStatus], [], []),
    'updateVolunteerStatus' : IDL.Func([IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };